### PR TITLE
Add TomlPropertyMetadata.Span and populate

### PR DESCRIPTION
**Pull request by lilith**
This populates for both TomlTable and custom classes. I added a basic unit test.

### CODE REVIEW

**Comment by lilith** [comment]
Fixes https://github.com/xoofx/Tomlyn/issues/66

**Comment by xoofx** [comment]
CI is failing with one test (unfortunately the logs are a bit messy on the CI)
I haven't checked locally but if you get a chance to have a look, thanks!

**Comment by lilith** [comment]
When I checked it out in Codespaces I couldn't get a full pass before I made changes, and it was a bit of a mess. Maybe I just couldn't get the environment right, but a [devcontainer.json](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#devcontainerjson) could help.

**Comment by lilith** [comment]
Turns out the syntax coordinates change when the line endings are crlf, so I stopped asserting those and everything passes.

**Pull request merged**
